### ISSUE TITLE
What is the license of the code?

### ISSUE THREAD

**Issue by gwding** [max-andr/provably-robust-boosting#2]
The paper looks super interesting and thanks for opensourcing the code!
Just wondering what is the license of and could you add it to the repo?

**Comment by max-andr** [comment]
Hi Gavin,

Thanks for the interest in our paper! 
I will clarify this and get back to you in a couple of days.

**Comment by max-andr** [comment]
I have added the license. It's BSD-3, i.e. it's very permissive.

Please let me know if you need some help with the code. I'd be glad to help!
